### PR TITLE
Use recycle instead of package for refactoring

### PR DESCRIPTION
**Pull request by willrstern**
How do you feel about ♻️  instead of 📦  for `refactor`?

### CODE REVIEW

**Comment by poeticninja** [comment]
I was just looking at all of the icons and they seem to make sense. The 📦 was the only one out of place. I also like the idea of ♻️.

**Comment by dannyfritz** [comment]
Yeah, I like it better too. Sometime this week I'll bump the major semver and change it.

**Comment by ericclemmons** [comment]
Close this PR, because it was my idea!!! :trollface:

**Comment by dannyfritz** [comment]
v2.0.0 released https://github.com/dannyfritz/commit-message-emoji/releases/tag/2.0.0

**Pull request merged**
