### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vkhv**

### CODE REVIEW

**Comment by dannyfritz** [comment]
Why ladybug?

**Comment by vkhv** [comment]
Because when we are thinking about software bugs we do not  imagine caterpillar.
We imagine something like this: 

Снимок экрана 2019-10-10 в 11 15 34

Isn't ?

**Comment by vkhv** [comment]
@dannyfritz any feedback pls

**Comment by dannyfritz** [comment]
While I see what you are getting at, `bug` in emoji is classified as a caterpillar: https://emojipedia.org/bug/
* May also be used for metaphorical senses of bug.

Lady Beetle: https://emojipedia.org/lady-beetle/
  * May be used a symbol of good luck.

I am going to keep bug as :bug: for now

**Pull request closed without merging**
