### PR TITLE
Added the colon shorthand so you won't have to look it up

### PR DESCRIPTION
**Pull request by acidjazz**
Makes it a lot easier for me to refer/use this sheet

### CODE REVIEW

**Comment by dannyfritz** [comment]
Duplicate of https://github.com/dannyfritz/commit-message-emoji/pull/23

**Comment by dannyfritz** [comment]
For future markdown endeavors though, surround it with backticks
```
`:bug:`
```
makes `:bug:`

**Comment by acidjazz** [comment]
@dannyfritz thanks, well even though you disagree on using the colon version, it'd still be helpful for people that do like to use it, right? Maybe just put that you suggest copy+pasting the character since it doesn't render all the time?

**Comment by dannyfritz** [comment]
There is some discussion of it here: https://github.com/dannyfritz/commit-message-emoji/issues/4

All in all, my thoughts are that Unicode is a well supported standard and basecamp codes are not. The other thing is there are basecamp codes that don't have Unicode emojis.

**Comment by acidjazz** [comment]
True, and I agree, but I hate cut+pasting for a git commit message, while typing the colon codes is easy, and I don't really care what shows up in terminal in most of our projects, all of our coordination is in GH, and I think that goes for others as well.  I'd rather use your readme as a reference than keep this fork.

**Comment by acidjazz** [comment]
@dannyfritz how about we agree to disagree and I add something like this

# install emojify
```shh
brew install emojify
```

# add this line to your `.bashrc` or `.zshrc`
```bash
gc() { git commit -am "$(emojify "$*")" }
```

This will let you write in colon and translate it into unicode

**Comment by dannyfritz** [comment]
Yeah, absolutely in adding it as an integration.

**Pull request closed without merging**
