### PR TITLE
Add Removal 🗑️

### PR DESCRIPTION
**Pull request by Zhastreaus**
There are things that we tend to remove such as a feature on projects so I added 🗑.
Thoughts?

### CODE REVIEW

**Comment by dannyfritz** [comment]
I feel this falls into the 💩 "deprecated" category. Thoughts?

**Comment by Zhastreaus** [comment]
Isn't deprecation different from removal?
Like, React's .createClass() is **deprecated** in v15.6
And then it will be **removed** on future version (say, v16)

**Comment by BrooksPatton** [comment]
I agree with @Zhastreaus. The 💩 would be there for the deprecated features. But you need to gather those up every once in a while and toss them into the 🗑 before the start stinking up the ~yard~ I mean codebase 😄

**Comment by dannyfritz** [comment]
Would there ever be a removal without a deprecation?

**Comment by w3cj** [comment]
Deprecation comes first. Then removal after a major version bump.

**Comment by dannyfritz** [comment]
I feel it is 5 for and 1 against at this point. Anyone else have a thought for not adding this?

**Comment by jeremiahboswell** [comment]
It's worth mentioning that Atom's [contributing.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#styleguides) specifies using :fire: for code removal. If :fire: has a unicode equivalent, I think that would be preferable to the unicode-only trashbin for users who prefer to use the Github codes.

**Comment by wesvetter** [comment]
@jeremiahboswell I just discovered GitHub and Slack both support :wastebasket: via `:wastebasket:`

**Comment by dannyfritz** [comment]
I slept on it for a while, but it has grown on me. Thanks for the PR!

**Pull request merged**
